### ISSUE TITLE
GetArtistAlbums album model

### ISSUE THREAD

**Issue by JWvdPol** [kaaes/spotify-web-api-android#115]
I'm trying to get albums of artist but not all the property's of the albumPager items are set. I need the release_date property but this is null.

1 = {kaaes.spotify.webapi.android.models.Album@5490} 
 artists = null
 copyrights = null
 external_ids = null
 genres = null
 popularity = null
 release_date = null
 release_date_precision = null
 tracks = null
 album_type = "album"
 available_markets = {java.util.ArrayList@5521}  size = 59
 external_urls = {com.google.gson.internal.LinkedTreeMap@5522}  size = 1
 href = "https://api.spotify.com/v1/albums/4LTwE2beptbYBHt8000N84"
 id = "4LTwE2beptbYBHt8000N84"
 images = {java.util.ArrayList@5525}  size = 3
 name = "White Reaper Does It Again"
 type = "album"
 uri = "spotify:album:4LTwE2beptbYBHt8000N84"
 shadow$_klass_ = {java.lang.Class@5346} "class kaaes.spotify.webapi.android.models.Album"
 shadow$_monitor_ = -1982144154

**Comment by JMPerez** [comment]
@JWvdPol The response from the Web API for artist's albums doesn't include the `release_date` (see [Get an Artist’s Albums](https://developer.spotify.com/web-api/get-artists-albums/).

You need to make an additional request to fetch full album objects. You can use `getAlbums(ids)` for this.
