### ISSUE TITLE
Audio features missing from API

### ISSUE THREAD

**Issue by ErikAndreas** [kaaes/spotify-web-api-android#116]
https://developer.spotify.com/web-api/get-audio-features/ and get-several-audio-features seem to be missing from the api? 

In addition to #58 the audio features has a field 'analysis_url' which is an entry to the echonest api/data which might be a natural place to start with regards to echonest features, specially since echonest have stopped issuing api keys and their api's will be replaced by official spotify api's, see http://developer.echonest.com/

**Comment by kaaes** [comment]
These endpoint have been added in https://github.com/kaaes/spotify-web-api-android/pull/119
