### ISSUE TITLE
GetMySavedTracks returns 20 tracks, regardless

### ISSUE THREAD

**Issue by chjan** [kaaes/spotify-web-api-android#133]
Seemingly, 20 tracks are always returned, even if another number less than 51 is requested. Not a big issue since 20 works just fine, but herebye reported as a discrepancy to the API specification. 50 tracks worked a year ago.

**Comment by JMPerez** [comment]
@chjan Are you using the method to which you can pass `options` (https://github.com/kaaes/spotify-web-api-android/blob/ac9b499a58d05364eb8fe0cf154d1247a6af9581/spotify-api/src/main/java/kaaes/spotify/webapi/android/SpotifyService.java#L1109) ?

**Comment by chjan** [comment]
Confirmative. I use these options, then with length set to 50. 20 is returned. Maybe something wrong here from my side?

`Map<String, Object> options = new HashMap<String, Object>();
        {
            options.put("offset", offset);
            options.put("length", length);
        }`

**Comment by XbakkeyX** [comment]
You should be using "limit" option, not "length"

**Comment by JMPerez** [comment]
@XbakkeyX Thanks for spotting this! Yes, the parameter should be `limit`, as described on [the documentation](https://developer.spotify.com/web-api/get-users-saved-tracks/).

I'll close this ticket since this doesn't seem to be a bug in the library.
