### ISSUE TITLE
Retrofit Error 401 'No token set' but token is set and works in postman

### ISSUE THREAD

**Issue by Ookean** [kaaes/spotify-web-api-android#171]
So when im trying to set the token as shown in the example provided by kaaes
```
SpotifyApi api = new SpotifyApi();

// Most (but not all) of the Spotify Web API endpoints require authorisation.
// If you know you'll only use the ones that don't require authorisation you can skip this step
api.setAccessToken("myAccessToken");

SpotifyService spotify = api.getService();
```
When I now call a service on my spotify object, i get a 401 "unauthorized" alltough i see that my token is valid and the rest call should work. I tested my token with postman on the same url as provided in the rest api by kaees and i retrieve the desired values. 

Does anyone know what I did wrong or is it a bug?

**Comment by Ookean** [comment]
Okay apparently i had an issue with an other dependency I used. Removing the other dependency and rebuilding the app worked out for me.

**Comment by willccoates** [comment]
I have this error as well. Im thinking my issue is how i defined the scope when creating the token. I did the following to set the scope, please let me know if it is incorrect.

AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(CLIENT_ID, AuthenticationResponse.Type.TOKEN, REDIRECT_URI);

builder.serScopes(new String[]{"playlist-read-private", "playlist-read-collaborative});

After authentication occurs, i receive a valid token that when tested on the spotify api client online it returns the correct information in JSON. Any information would help!
