### ISSUE TITLE
Running the tutorial, but: RetrofitError: okio.Buffer

### ISSUE THREAD

**Issue by chjan** [kaaes/spotify-web-api-android#20]
Is this the place to ask for help on this RetrofitError issue? I suspect okio is a part of the OkHttp, but this error message says me nothing. I am doing the "getAlbum" tutorial without an accesstoken.

**Comment by kaaes** [comment]
Yes, this is the good place for it :)
Can you please post the error that you're seeing? How are you building the RestAdapter?

**Comment by chjan** [comment]
The error in logcat is simply this: "RetrofitError: okio.Buffer". Nothing more. 

As in the readme tutorial, I try to search for artist and album, both result in this error.  It arrives in the "failure" callback.

Note I am using NetBeans.

**Comment by kaaes** [comment]
I just tried and I'm not able to reproduce this. Is there anything in the error that comes to the failure callback? Maybe you could debug and see where the error originates?

**Comment by chjan** [comment]
Could you please verify that I have the same libraries and in same versions of libraries as you do? Could there be any limitations as to which Android version is valid for this system ?

**Comment by chjan** [comment]
I found the error by a push on "The wild guess button" as follows: Since the retrofit error contained the string "okio.Buffer", I located here on github its project page: https://github.com/square/okio/blob/master/README.md. This page is more informative than the link given for OkHttp even if I feel pretty ignorant of the actual difference of OkHttp and okio ? (I haven't got a clue on what is what here, and I would normally prefer to not understand all underlying details when using an API)

Anyway, I found on that page a link to the latest jar, and included this in my build. Now everything is working fine. Do I still need OkHttp as well ? Don't know.

The question mark for me is why the build and run does not report the missing library okio.jar ? I have never before seen that a missing jar is passing under the radar like that. 

Here are the included libraries used, not sure all of them are mandatory. Hope this will help others. Actually, it is suggested to add some information to the Readme regarding these libraries, i.e. the correct list of jars to include when building.

![image](https://cloud.githubusercontent.com/assets/69140/5761895/d8baa39e-9cde-11e4-83c7-1f3805eed0e8.png)

**Comment by chjan** [comment]
Kaaes, I have asked about this Retrofit error in their project at Git, see it here: 
https://github.com/square/retrofit/issues/707#issuecomment-70227329

Part of the response is this "The issue is probably that the Spotify API is distributing a lean JAR, without any transitive dependencies."

The issue becomes twofold: 1. the okio.jar is not reported missing during build process. I don't understand why not. 2. This missing library causes "ClassDefNotFound" exception, however it is severly complicating that the retrofitError, a subclass of RunTimeException, does not report this to the log system (logCat). 

Q: Would it be a good thing if the Spotify Web API distributed a complete set of JAR libraries that would work out of the box, i.e. include all relevant JARs. At least, that would save a lot of time for ignorant newcomers in which category I put myself.

**Comment by kaaes** [comment]
Thank you for looking into this. Nice research!
I noticed that this library is using outdated versions of retrofit and OkHttp. I am planning to update them today. I can add a task to build files that will build a fat jar with all dependencies in it. I will also update he documentation to include info about possible dependency issues.

I am still not sure why it's okio if the dependency is on okhttp but maybe that's some internal ok stuff.

**Comment by chjan** [comment]
Excellent. I shall try that new "fatened up" version. 

Meanwhile another Q: This API has methods that uses user-id as input, but I cannot find any authentication api here? Does this mean that it is necessary to use the Android SDK to authenticate the user, then "revert" back to this api for its intended usage? If not, what is recommended way to authenticate the user from an Android app that connects to Spotify via this api?

**Comment by kaaes** [comment]
This library doesn't have authentication module as it was initially created as an extension to the SDK. But there's a project based on this one that added auth functionality https://github.com/Drivemode/SpotifyApi

**Comment by chjan** [comment]
ok, but before trying that, will I then possibly face the same issues that was discussed above with a lean Jar etc? Are there other limitations you are aware of? (If I understand things correctly, the WEB API is available for commercial apps, while the android sdk is not, which makes it interesting to have the authentication module included in this api, or the other one you linked).

**Comment by kaaes** [comment]
I strongly suspect you're right about lean library and think this other project builds as aar not jar which might be also an issue (?) Probably the author knows more :)

**Comment by chjan** [comment]
The API seems to contain all I need except the authentication. Couldn't you inject the authentication module in this api? It is not much code in the sdk tutorial (authentication tutorial tested and working today). https://developer.spotify.com/technologies/spotify-android-sdk/tutorial/

Regarding AAR: Yes, this is an unfortunate issue at least for NetBean based development. However, I could decode the AAR at least partly right into a JAR system for the Android SDK case.

The best of all for those of us who just use your library API but don't really need to build our local version, would be to have available a ready built JAR and (I suppose) AAR. Would that be possible?

**Comment by kaaes** [comment]
This discussion is starting to touch multiple subjects ad it would be best to move it to separate issues.
I think both your suggestions are good and would make valuable additions to this project.

**Comment by chjan** [comment]
Yes agree. Invite me into such discussion via e.g. chj@hdsoundlab.com as relevant. At the moment, I shall use authentication via Android SDK, the rest from kaaes api. Your help thus far was appreciated.
