### ISSUE TITLE
getPlaylistTracks missing offset and limit parameter.

### ISSUE THREAD

**Issue by Wolftein** [kaaes/spotify-web-api-android#35]
Hello!, would you consider to add getPlaylistTracks with offset and limit parameter?

UPDATE: Same for searchTracks.

Thanks!.

**Comment by JohnnyCrazy** [comment]
Hey @Wolftein 

You can specify the limit and offset via the `Map<String, Object> options` parameter.
An example call:
```
Map<String, Object> options = new Map<String, Object>();
options.put(SpotifyService.OFFSET, 50) // 50 Offset
options.put(SpotifyService.LIMIT, 20) // 20 Limit
spotifyService.getPlaylistTracks(userId, playlistId, options);
```

**Comment by Wolftein** [comment]
Hi @JohnnyCrazy , oh thanks!, didn't knew that :D.

**Comment by psstoyanov** [comment]
Hi, I'm trying to create the map so that I can set a limit on the search results, however I get an error "Map is abstract; cannot be instantiated".
Could you help me figure out where or what I am doing wrong?

SpotifyService spotify = api.getService();
            final Map<String, Object> options = new Map<String, Object>();
            options.put(SpotifyService.COUNTRY, "GB");
            spotify.searchArtists("Test",options);
