### ISSUE TITLE
gradle version

### ISSUE THREAD

**Issue by Watke** [kaaes/spotify-web-api-android#36]
Hej,

I was wondering which gradle version, and gradle build tool you use?

![screen shot 2015-03-12 at 19 21 57](https://cloud.githubusercontent.com/assets/1387249/6626231/13cc2edc-c8ed-11e4-9c84-1212e10bcfda.png)

**Comment by kaaes** [comment]
I use it with gradle plugin 1.0.0 but I think it should work with anything > 0.14.3
From google: https://code.google.com/p/android/issues/detail?id=80003

**Comment by kaaes** [comment]
@Watke is there anything else you need help with regarding this issue? I'd close it otherwise
