### ISSUE TITLE
Retrofit 404 when trying to retrieve tracklist for _shared_ playlists 

### ISSUE THREAD

**Issue by frel** [kaaes/spotify-web-api-android#37]
Hi, thanks for the great effort you're making for the SDK. I hope I'm asking in the correct place.

I have an issue where calling `spotify.getPlaylistTracks(mySpotifyUser.id, playlist.id, trackMap);` on a _shared_ playlist gives a **404** error in Retrofit. It looks like only shared playlists are affected in my case at least.
```
Playlist.name 					= Trening
Playlist id 					= 2RzxCgFbJSsNWPzNAAL7WA
Playlist type 					= playlist
Playlist is public 				= false
Playlist is collaborative 		= false
Playlist owner.type 			= user
Playlist description			= null
Playlist href 					= https://api.spotify.com/v1/users/117390626/playlists/2RzxCgFbJSsNWPzNAAL7WA
```

Am I missing something? I'm using the following scopes:
```"user-read-private", "playlist-read", "playlist-read-private", "streaming", "user-follow-read"```

Thanks for helping out!
- Fredrik

**Comment by thelinmichael** [comment]
@frel, is mySpotifyUser.id the playlist's owner?

**Comment by frel** [comment]
@thelinmichael  My apologies! I cannot believe I actually missed that one. You are indeed right. I was providing the logged in userId and not the playlist.owner.id. Thank you very much, and have a nice day :)
