### ISSUE TITLE
Playlist Pager does not have track items

### ISSUE THREAD

**Issue by acidmath** [kaaes/spotify-web-api-android#44]
When using the getPlaylists function, when I ask the playlist pager for the track items of a playlist, it is always null. 

Here is the code I am using in the SpotifyCallback.

```
public void success(Pager<Playlist> playlistPager, Response response) {
    for (Playlist playlist : playlistPager.items) {
        if(playlist.tracks.items!=null) { 
            // it is always null
            for (PlaylistTrack track : playlist.tracks.items) {
                convertedPlaylist.trackKeyStrings.add(track.track.id);
            }
        }
    }
}
```

**Comment by JohnnyCrazy** [comment]
Hey,

I think `getPlaylists` is using the wrong Playlist.  
Currently, it's using the full `Playlist`-Object, which contains tracks wrapped inside a paging-object.
However, (getPlaylists)[https://developer.spotify.com/web-api/get-list-users-playlists/] seems to return a SimplePlaylist, which only supplies the amount of tracks & the API endpoint for the tracks.

To fix this, we just need to exchange `Playlist` with `PlaylistSimple` in all `getPlaylists`-methods

**Comment by z0lope0z** [comment]
+1
