### ISSUE TITLE
problem using asynchronous removeTracksFromPlaylist callback

### ISSUE THREAD

**Issue by acidmath** [kaaes/spotify-web-api-android#47]
This is my implementation

```
TrackToRemove trackToRemove = new TrackToRemove();
trackToRemove.uri = myTrack.spotifySongUrl;

TracksToRemove tracksToRemove = new TracksToRemove();
tracksToRemove.tracks = new LinkedList<TrackToRemove>();
tracksToRemove.tracks.add(trackToRemove);

mySpotifyService.removeTracksFromPlaylist(
    playlistOwner, playlistKey, tracksToRemove, new SpotifyCallback<SnapshotId>() {

        @Override
        public void failure(SpotifyError spotifyError) {
              Log.e(TAG, "error deleting", spotifyError);
        }

        @Override
        public void success(SnapshotId snapshotId, Response response) {
            removeFromView(myTrack);
        }
    }
);
```

This is the error from 3 devices:
kaaes.spotify.webapi.android.SpotifyError: retrofit.RetrofitError: DELETE does not support writing

**Comment by kaaes** [comment]
I tried your code and it actually worked for me but I also found a discussion that might be relevant: https://github.com/square/retrofit/issues/426
Do you think this issue might be related to the HTTP client you're using?

**Comment by acidmath** [comment]
Most of the related material I am seeing suggests doing a POST command with the same arguments, but I'm pretty sure I can't just rewire the backend like that. I thought the http client was just the restadapter that's provided by the spotify sdk, but I will have to check into it more after the weekend.

**Comment by kaaes** [comment]
According to the linked discussion DELETE with body should work correctly with OkHttp >= 1.5 which is the client Retrofit is using.
For the reference these are the dependencies I was testing with (on Android 5.1, 4.3 and 4.1):
```java
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar']) // for spotify-web-api-android-0.1.0.jar
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
}
```

**Comment by acidmath** [comment]
compile 'com.squareup.okhttp:okhttp:2.2.0'

This line fixed the problem for me. I think my picasso plugin might have been causing a conflict. Thank you!

**Comment by kaaes** [comment]
Great :) I'm closing the issue
