### ISSUE TITLE
getRelatedArtists (ArtistPager.items = null)

### ISSUE THREAD

**Issue by digitaldesaster** [kaaes/spotify-web-api-android#51]
could you please check this. this call does not work for me. i see that the retrofit call works and it fetches items. but the ArtistPager.items are null.

thanks
Alex

**Comment by kaaes** [comment]
Please try getting the latest version. This bug has been already fixed (`getRelatedArtists` should return `Artists` not `ArtistPager`)

**Comment by digitaldesaster** [comment]
ok, thx for feedback
