### ISSUE TITLE
Add proper versioning

### ISSUE THREAD

**Issue by kaaes** [kaaes/spotify-web-api-android#52]
It's been on version 0.1.0 since the beginning. We should start versioning it to reflect changes made to the library.

**Comment by d-kunin** [comment]
We have decided to go with [Semantic Versioning 2.0.0](http://semver.org/). That means that API might be changed until we reach 1.0.0 version.

###### Semver in nutshell:
Version has a format MAJOR.MINOR.PATCH. We increment *patch* when we have backward compatible bug fixes, we increment *minor* for backward compatible API changes. If we make breaking changes, we increment *major*. Please check more detailed explanation [here](http://semver.org/).

###### Milestones and issue tags
It is very nice to have milestones with defined scope. Therefore issues should have a milestone tag assigned.

**Comment by d-kunin** [comment]
Also declared versioning policy in #57
