### ISSUE TITLE
getPlayListTracks, RetrofitError: 404 due to local MP3 files

### ISSUE THREAD

**Issue by digitaldesaster** [kaaes/spotify-web-api-android#53]
Hi, 

If somebody has local mp3 files in its playlist, the getPlayListTracks throws a 404 error due to the AlbumType = null. 

would it be possible to ignore local mp3 files? 

you can try this list.

thanks in advance
Alex

1121798449
10WUZITIe8MCurCTYMuzQf

**Comment by kaaes** [comment]
I just ran this code:

```java
spotify.getPlaylistTracks("1121798449", "10WUZITIe8MCurCTYMuzQf", new SpotifyCallback<Pager<PlaylistTrack>>() {
    @Override
    public void success(Pager<PlaylistTrack> playlistTrackPager, Response response) {
        Log.d(TAG, String.valueOf(playlistTrackPager.total));
    }

    @Override
    public void failure(SpotifyError error) {
        Log.e(TAG, error.getMessage());
    }
});
```

And got `200` in response. What is the error message you're getting?

**Comment by digitaldesaster** [comment]
Hi Kaaes, sorry it was my mistake. (swapped userid / playlistid)

everything works fine. 

thank you
Alex
