### ISSUE TITLE
Retrofit error: Unexpected at SpotifyApi() 

### ISSUE THREAD

**Issue by venkateshappea** [kaaes/spotify-web-api-android#60]
Hi,
When I run wrapper class example or any SpotifyApi method such as getTrack() in my android studio project, I get a retrofit unexpected error. I did some further research and I discovered that I might also need the   compile 'com.squareup.okio:okio:1.2.0'. I included all the libraries that was said to be included in the spotify web api wrapper, I'm wondering if I'm missing anything. My gradle file is as follows:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // This library handles authentication and authorization
    compile 'com.spotify.sdk:spotify-auth:1.0.0-beta10@aar'

    // This library handles music playback
    compile 'com.spotify.sdk:spotify-player:1.0.0-beta10@aar'

    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.squareup.okio:okio:1.2.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'

}
do you know If i'm missing any .jar files?

**Comment by d-kunin** [comment]
Dont you need 'compile 'com.squareup.okhttp:okhttp:2.2.0'' as well?
