### ISSUE TITLE
Having problems building the jar

### ISSUE THREAD

**Issue by theBoyMo** [kaaes/spotify-web-api-android#64]
Executing 
./gradlew jar

results in the following error message
Task 'jar' not found in root project 'spotify-web-api-android'

and the build fails. Any ideas as to the solution.

Bill

**Comment by d-kunin** [comment]
@theBoyMo please use `./gradlew assemble` and collect `spotify-web-api-android-0.1.0.aar` from build/outputs/aar

sorry for confusion, I will update the doc right away

**Comment by theBoyMo** [comment]
Cheers, that worked a treat.

**Comment by RedDev112** [comment]
What do you mean by 'collect' `<spotify-web-api-android-0.1.0.arr>`? What do I do with it, so that I can build the library into a jar?

**Comment by theBoyMo** [comment]
I simply placed the resulting aar file in the project's app/libs folder,  amended the app build.gradle file and performed a sync. Spotify-web-api, RetroFit, OkHttp and Gson libraries now appear in the External Libraries folder and I can access the various Spotify classes from within an activity or fragment.

**Comment by kalendamoise** [comment]
If you only need the jar, do the following: 
1. go to build/outputs/aar
2. unzip spotify-web-api-android-0.1.0.arr 
3. rename your classes.jar to spotify-web-api-android-0.1.0.jar 
    mv classes.jar spotify-web-api-android-0.1.0.jar
4. use the jar file into your project
