### ISSUE TITLE
Cannot build the jar with the 'gradlew jar' command

### ISSUE THREAD

**Issue by PaulPerret** [kaaes/spotify-web-api-android#66]
Following the directions to build the jar file...
After cloning the project, hen I try to build the jar with the './gradlew jar' command, it fails with the following error:
Task 'jar' not found in root project 'spotify-web-api-android'.

Also worth mentioning that the user will need to update the local.properties file with the location of their local Android SDK installation.

**Comment by khuezy** [comment]
+1, I am having the same issue.

**Comment by WhiteDawn** [comment]
+1 this build property was removed during the merge on commit 29656fc
In the meantime commit 17d5491 builds fine with gradlew jar

**Comment by d-kunin** [comment]
@PaulPerret @khuezy  @WhiteDawn 
Please read [README.md](https://github.com/kaaes/spotify-web-api-android/blob/master/README.md), it was updated and now it says to use `./gradlew assemble` command to build 'aar' file, not 'jar' file.

**Comment by PaulPerret** [comment]
Just a note, the README.md still contains the instructions to build the jar with the gradlew jar command under the Build section at the top.

**Comment by kaaes** [comment]
@PaulPerret good catch. I'll fix it. Thanks!

**Comment by d-kunin** [comment]
@PaulPerret thank you, to my shame I haven't noticed it. Sorry for the mess.
