### ISSUE TITLE
Add distribution of an artefact via repository

### ISSUE THREAD

**Issue by d-kunin** [kaaes/spotify-web-api-android#67]
It is quite cumbersome to make users to build library themself, so we should add an easy-to-integrate feature. The first option is to use maven central.

**Comment by wiyarmir** [comment]
Unfortunately, projects to be synced to Maven Central must be hosted on [one of the pre-approved hostings](http://maven.apache.org/guides/mini/guide-central-repository-upload.html#Approved_Repository_Hosting)

Consider using Sonatype OSSRH (OSS Repository Hosting), in case you accept their [terms of service](http://central.sonatype.org/pages/central-repository-producer-terms.html). This is the hosting used by many Android-based projects e.g Robolectric.

I am willing to assist onboarding the project into Sonatype's hosting if the project collaborators consider it the way to go.

**Comment by jitpack-io** [comment]
Hi!

Have you considered using JitPack? The current master version is available there:
https://jitpack.io/#kaaes/spotify-web-api-android/b0a4c2dad3
Would be nice if there was a new GitHub release of spotify-web-api-android.

**Comment by kaaes** [comment]
Thank you for those suggestions. We are looking into the options for hosting artifacts for this project together with other Spotify Android SDK libraries so your input is really useful. If you have more, please keep it coming!
I will update this thread when we know more.

**Comment by kaaes** [comment]
I think it would be good to tackle this finally. Seems like we have two options here:

Go with Jitpack as it looks super simple!
Publish project in Maven Central as it is The Repository
I would love to know your opinions!
(ping @d-kunin @JMPerez @thelinmichael)

**Comment by kaaes** [comment]
:boom: & done I'll close this now. Thanks @jitpack-io
