### ISSUE TITLE
jacoco.exec System Error

### ISSUE THREAD

**Issue by digitaldesaster** [kaaes/spotify-web-api-android#72]
I am using this library since march and didn't updated the jar/aar file since today.

I am getting the following error while creating a new API object which the latest code. 

SpotifyApi SpotifyApi = new SpotifyApi();

First part of the log shows the error message after replacing the old "jar" from March with the new "aar" from today. The second part shows the error message after rebuilding the project. 

stopping and restarting the app does not show this error message.

i wonder if i should ignore this?

best regards
Alex

06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:456)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at kaaes.spotify.webapi.android.SpotifyApi.$jacocoInit(SpotifyApi.java)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at kaaes.spotify.webapi.android.SpotifyApi.<init>(SpotifyApi.java)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at com.alexfillips.spotifyremote.Fragment.MainFragment.GetFeaturedPlayLists(MainFragment.java:1468)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at com.alexfillips.spotifyremote.Fragment.MainFragment$6.run(MainFragment.java:1445)
06-09 14:20:48.333  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
06-09 14:20:48.334  23514-23543/com.alexfillips.emmaTV W/System.err﹕ Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
06-09 14:20:48.334  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.Posix.open(Native Method)
06-09 14:20:48.335  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-09 14:20:48.335  23514-23543/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:442)
06-09 14:20:48.335  23514-23543/com.alexfillips.emmaTV W/System.err﹕ ... 11 more
06-09 14:20:48.530  23514-23514/com.alexfillips.emmaTV W/Settings﹕ Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.

06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at kaaes.spotify.webapi.android.SpotifyApi.$jacocoInit(SpotifyApi.java)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at kaaes.spotify.webapi.android.SpotifyApi.<init>(SpotifyApi.java)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at com.alexfillips.spotifyremote.Fragment.MainFragment.GetFeaturedPlayLists(MainFragment.java:1468)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at com.alexfillips.spotifyremote.Fragment.MainFragment$6.run(MainFragment.java:1445)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.Posix.open(Native Method)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-09 14:22:18.242  23701-23733/com.alexfillips.emmaTV W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:442)

**Comment by kaaes** [comment]
@digitaldesaster this should be now fixed
