### ISSUE TITLE
Can't seem to find .aar...newbies question I guess

### ISSUE THREAD

**Issue by amrfarid140** [kaaes/spotify-web-api-android#77]
when I do ./gradlew on windows no build directory or .aar file is created throughout my windows files.

![image](https://cloud.githubusercontent.com/assets/5002609/8220557/1ef9f05e-154c-11e5-931e-086d34e8fc91.png)
 any ideas on what to do?

**Comment by kaaes** [comment]
@amrfarid140 the syntax of gradle commands is `./gradlew <task name>` (you can see it in the console output in your screen). To build the project you should run `./gradlew assemble` (or in your case `gradlew assemble`).
You can find more details in the [README.md file](https://github.com/kaaes/spotify-web-api-android).

**Comment by carter3689** [comment]
I'm also having an issue finding the aar file as well. When I run the given set of commands in the README file I receive this error.

iMac:~ jc$ /Users/jc/Documents/spotify-web-api-android./gradlew assemble
-bash: /Users/jc/Documents/spotify-web-api-android./gradlew: No such file or directory

Any Suggestions?

**Comment by kaaes** [comment]
@carter3689 try first going to the directory that the project is checked out to and from inside this directory call the gradle command:
```
cd /Users/jc/Documents/spotify-web-api-android
./gradlew assemble
```

**Comment by ivamluz** [comment]
Hi,

I'm also facing issues to generate the .aar file.

Following is my console output:

    iluz spotify-web-api-android (master) > ./gradlew assemble
    :spotify-api:compileLint
    :spotify-api:copyDebugLint UP-TO-DATE
    :spotify-api:mergeDebugProguardFiles
    :spotify-api:preBuild UP-TO-DATE
    :spotify-api:preDebugBuild UP-TO-DATE
    :spotify-api:checkDebugManifest
    :spotify-api:prepareDebugDependencies
    :spotify-api:compileDebugAidl
    :spotify-api:compileDebugRenderscript
    :spotify-api:generateDebugBuildConfig
    :spotify-api:generateDebugAssets UP-TO-DATE
    :spotify-api:mergeDebugAssets
    :spotify-api:generateDebugResValues
    :spotify-api:generateDebugResources
    :spotify-api:packageDebugResources
    :spotify-api:processDebugManifest
    :spotify-api:processDebugResources
    :spotify-api:generateDebugSources
    :spotify-api:processDebugJavaRes UP-TO-DATE
    :spotify-api:compileDebugJava
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    :spotify-api:unzipJacocoAgent
    :spotify-api:instrumentDebug
    :spotify-api:packageDebugJar
    :spotify-api:compileDebugNdk UP-TO-DATE
    :spotify-api:packageDebugJniLibs UP-TO-DATE
    :spotify-api:packageDebugLocalJar
    :spotify-api:packageDebugRenderscript UP-TO-DATE
    :spotify-api:bundleDebug
    :spotify-api:compileDebugSources
    :spotify-api:assembleDebug
    :spotify-api:copyReleaseLint UP-TO-DATE
    :spotify-api:mergeReleaseProguardFiles
    :spotify-api:preReleaseBuild UP-TO-DATE
    :spotify-api:checkReleaseManifest
    :spotify-api:prepareReleaseDependencies
    :spotify-api:compileReleaseAidl
    :spotify-api:compileReleaseRenderscript
    :spotify-api:generateReleaseBuildConfig
    :spotify-api:generateReleaseAssets UP-TO-DATE
    :spotify-api:mergeReleaseAssets
    :spotify-api:generateReleaseResValues
    :spotify-api:generateReleaseResources
    :spotify-api:packageReleaseResources
    :spotify-api:processReleaseManifest
    :spotify-api:processReleaseResources
    :spotify-api:generateReleaseSources
    :spotify-api:processReleaseJavaRes UP-TO-DATE
    :spotify-api:compileReleaseJava
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    :spotify-api:packageReleaseJar
    :spotify-api:compileReleaseNdk UP-TO-DATE
    :spotify-api:packageReleaseJniLibs UP-TO-DATE
    :spotify-api:packageReleaseLocalJar UP-TO-DATE
    :spotify-api:packageReleaseRenderscript UP-TO-DATE
    :spotify-api:bundleRelease
    :spotify-api:compileReleaseSources
    :spotify-api:assembleRelease
    :spotify-api:assemble
    
    BUILD SUCCESSFUL
    
    Total time: 3.584 secs
    iluz spotify-web-api-android (master) > ll
    total 80
    drwxr-xr-x 7 iluz iluz 4096 Jul 23 23:18 ./
    drwxr-xr-x 3 iluz iluz 4096 Jul 23 23:17 ../
    -rw-r--r-- 1 iluz iluz  601 Jul 23 23:18 build.gradle
    drwxr-xr-x 8 iluz iluz 4096 Jul 23 23:18 .git/
    -rw-r--r-- 1 iluz iluz   80 Jul 23 23:18 .gitignore
    drwxr-xr-x 3 iluz iluz 4096 Jul 23 23:18 gradle/
    drwxr-xr-x 3 iluz iluz 4096 Jul 23 23:18 .gradle/
    -rw-r--r-- 1 iluz iluz  378 Jul 23 23:18 gradle.properties
    -rwxr-xr-x 1 iluz iluz 5080 Jul 23 23:18 gradlew*
    -rw-r--r-- 1 iluz iluz 2406 Jul 23 23:18 gradlew.bat
    -rw-r--r-- 1 iluz iluz 1079 Jul 23 23:18 LICENSE
    -rw-r--r-- 1 iluz iluz   86 Jul 23 23:18 local.properties
    -rw-r--r-- 1 iluz iluz 5295 Jul 23 23:18 README.md
    -rw-r--r-- 1 iluz iluz 1961 Jul 23 23:18 release.gradle
    -rw-r--r-- 1 iluz iluz   23 Jul 23 23:18 settings.gradle
    drwxr-xr-x 4 iluz iluz 4096 Jul 23 23:18 spotify-api/
    -rw-r--r-- 1 iluz iluz  398 Jul 23 23:18 .travis.yml
    drwxr-xr-x 2 iluz iluz 4096 Jul 23 23:18 .utility/

It used to work in a previous version, but it seems it stopped working since I have git pulled to d579e7f667a87b7b0c67a43d99e197a401aac3e9. Checked on 6ebc2dd32b0bdcd0faea74f17706f7f1be0eeff3 and the file is generated:

    iluz aar ((6ebc2dd...)) > ll
    total 32
    drwxr-xr-x 2 iluz iluz  4096 Jul 23 23:25 ./
    drwxr-xr-x 4 iluz iluz  4096 Jul 23 23:25 ../
    -rw-r--r-- 1 iluz iluz 22264 Jul 23 23:25 spotify-web-api-android-0.1.0.aar

Am I doing any dummy mistake here?

**Comment by ivamluz** [comment]
After performing a git bisect, it seems the issue (not sure if it's really an issue or if it's just the README file that needs to be updated), started on the following commit:

    commit c2f016a16d3050ea5ca7e33c7ee15a9ed9afed76
    Author: Dima Kunin <mr.kunin@gmail.com>
    Date:   Wed Jul 8 23:06:44 2015 +0200
    
        Separate module for library. Parcelable models
    
    :040000 040000 6b0dca3d015561893fdc4523bb5862531b13547f 6a56b6cb54e371537e02fc1c0efe134294d48e50 M  .utility
    :100644 100644 3021afd26fdf8def243735b698f9ed57aa23bdeb dd042666962180a4ef878281769b4e0080db8eb4 M  README.md
    :100644 100644 e8cc3164b475d94fb6eeb6bba95f2961948899c4 f60d624f353f9ec124fd0979997fcdde56be2389 M  build.gradle
    :100644 100644 5d08ba75bb97fd0f586f3c64e237c3439dbb5925 a3debbf1e069c9cc9b5349bd1d599aabad932d75 M  gradle.properties
    :040000 040000 4221140e92ed8e1739d4884e3e66b76b476062f0 68f4846a8b251ec84bd9bdd269b6c42a28753723 M  gradle
    :000000 100644 0000000000000000000000000000000000000000 2b1ff70aa9d60b809d6101f15a59e5adde7f5efc A  release.gradle
    :000000 100644 0000000000000000000000000000000000000000 7ae5004e98e3f65e0ecffd8e78832b4338d86a04 A  settings.gradle
    :000000 040000 0000000000000000000000000000000000000000 1eb60307fcc8c3e27506e93d01a9e017f8a5b559 A  spotify-api
    :040000 000000 84596b1f60d44e1cc313249584b473b8c814fd54 0000000000000000000000000000000000000000 D  src

**Comment by ivamluz** [comment]
And finally I can confirm it was caused by my lack of attention on reading the README. Was looking for a build folder on the root of the project, instead of looking inside spotify-api.

Sorry to bother with this.
