### ISSUE TITLE
api.GetService (cannot resolve method)

### ISSUE THREAD

**Issue by SayChunKim** [kaaes/spotify-web-api-android#78]
Log output D/Album failure﹕ retrofit.RetrofitError: 401 Unauthorized

api.GetService(); cannot resolved

**Comment by kaaes** [comment]
@SayChunKim I'm afraid I don't understand what your issue is. Could you be more specific?

**Comment by bkach** [comment]
I think @SayChunKim is trying to say that when trying to initialize the SpotifyService:

```
SpotifyService spotify = api.getService();
```

The getService method can't be resolved - even after importing 

```
kaaes.spotify.webapi.android.SpotifyService.
```

**Comment by kaaes** [comment]
It's unclear what this issue is about so I'm going to close it. Please feel free to open a new one if needed

**Comment by SayChunKim** [comment]
Sorry for late reply:

The issue was caused by old .jar file in download page for the wrapper. Managed to resolve it when build new one via gradlew.
