### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by arupsarkar** [kaaes/spotify-web-api-android#79]
Hi, I am getting 401 Unauthorized while using the spotify api wrapper, here is my code. 
spotifyAccessToken = Client secret code
The code is going in failure and I am getting 401 Unauthorized, the below code is in AsyncTask of android. I have given INTERNET access in Manifest xml file.

SpotifyApi api = new SpotifyApi();
api.setAccessToken(spotifyAccessToken);
SpotifyService spotify = api.getService();

            spotify.searchArtists("coldplay", new Callback<ArtistsPager>() {
                @Override
                public void success(ArtistsPager artistsPager, Response response) {
                    Log.v(LOG_TAG, response.getBody().toString());
                }

                @Override
                public void failure(RetrofitError error) {
                    Log.e(LOG_TAG, ">>>> Error : " + error.getMessage());
                }
            });

**Comment by JMPerez** [comment]
@arupsarkar The access token is not your client secret. You can read about the Spotify OAuth process on the [Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/).

You need to obtain a valid access token if you want to make that authenticate your request. Note that, in the case of the `search` endpoint, you are not required to authenticate the request, although it's always a good idea.

**Comment by kaaes** [comment]
@arupsarkar dis you manage to solve this problem or do you need more help?

**Comment by arupsarkar** [comment]
I would need a little bit of help in solving this problem, I will show you
what I have down so far so that you will understand.

**Comment by kaaes** [comment]
This is a very old issue so I'll close it. If you need more help please open a new one
