### ISSUE TITLE
[Question] Is AsyncTask required for calling SpotifyService.searchArtists?

### ISSUE THREAD

**Issue by ivamluz** [kaaes/spotify-web-api-android#81]
Hi,

Sorry to bother with this newbie question, but I'd like to know: is it necessary to call SpotifyService.searchArtists inside an AsyncTask or is this method already executed asynchronously?

Thanks,
Ivam

**Comment by kaaes** [comment]
@ivamluz this project uses [Retrofit](https://square.github.io/retrofit) which supports both synchronous and asynchronous requests. In short - you should call [synchronous `SpotifyService.searchArtists`](https://kaaes.github.io/spotify-web-api-android/javadoc/kaaes/spotify/webapi/android/SpotifyService.html#searchArtists(java.lang.String)) inside an AsyncTask but you don't need it if you call it [asynchronously with a callback](https://kaaes.github.io/spotify-web-api-android/javadoc/kaaes/spotify/webapi/android/SpotifyService.html#searchArtists(java.lang.String,%20retrofit.Callback)).
You can find more in Retrofit documentation

**Comment by ivamluz** [comment]
@kaaes, thanks for answering that. It's clear now.
