### ISSUE TITLE
Integration Sample Dependency Error

### ISSUE THREAD

**Issue by schordas** [kaaes/spotify-web-api-android#94]
In the [Integration into your Project](https://github.com/kaaes/spotify-web-api-android#integration-into-your-project) section you have a small error. The jar dependency is dated `compile(name:'spotify-web-api-android-0.1.0', ext:'aar')`. This should be updated to `compile(name:'spotify-web-api-android-0.1.1', ext:'aar')`.

**Comment by kuldip4u** [comment]
Thanks, it resolved error.

**Comment by kaaes** [comment]
Fixed!
