### ISSUE TITLE
getMe() causing the app to crash

### ISSUE THREAD

**Issue by sdp-23** [kaaes/spotify-web-api-android#95]
I am just starting to make an app and I am trying to start off by simply trying to get the user_id using the getMe() function. I don't really know much about the callbacks so I am using the one that returns a UserPrivate object. However the app starts by allowing the user to login and then it crashes saying the app stopped working. I am trying to print out the id on the screen to see if I got it but the app crashes before. 

Here is my code:
 

if (resultCode != RESULT_CANCELED && requestCode == REQUEST_CODE) {

            AuthenticationResponse response = AuthenticationClient.getResponse(resultCode, intent);
            TextView textView = (TextView) findViewById(R.id.text_view);
            if (response.getType() == AuthenticationResponse.Type.TOKEN) {
                // Response was successful and contains auth token
                Toast.makeText(getApplicationContext(), "Login Success!", Toast.LENGTH_LONG).show();
                textView.setText("Success");

                api.setAccessToken(response.getAccessToken());
                final SpotifyService spotify = api.getService();
                final String accessToken = response.getAccessToken();
                UserPrivate me = spotify.getMe();

                textView.setText("Success" + " - "+me.id);

I do not know why it is crashing.

**Comment by kaaes** [comment]
@sdp-23 not sure if you still need help with this but it's crashing because you're trying to execute a synchronous call on the UI thread. For this code to work you'd need to use the asynchronous call:
```java
spotify.getMe(new Callback<UserPrivate>() {
    @Override
    public void success(UserPrivate userPrivate, retrofit.client.Response response) {
    }

    @Override
    public void failure(RetrofitError error) {
    }
});
```

**Comment by sdp-23** [comment]
That code won't work actually. You can't make networking calls in the main thread. I fixed it with Async. You can put that or non-callback in Async and it should work.
